- name: yum install go-server
  sudo: yes
  yum: name=go-server-{{ GOCD_GO_VERSION }} state=present
  notify:
  - restart go-server

- name: replace /etc/default/go-server from package
  template: "src=go-server-defaults dest=/etc/default/go-server mode=0644 group={{ GOCD_GROUP }} owner={{ GOCD_USER }}"
  sudo: yes
  notify: restart go-server
  with_sequence: "count={{ GOCD_AGENT_INSTANCES }}"

- name: start go-server
  service: name=go-server state=started enabled=true
  notify:
     - ensure go-server running
